name: entrepreneur_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dropdown_search: ^5.0.6
  file_picker: ^6.1.1
  firebase_core: ^2.21.0
  firebase_messaging: ^14.7.3
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_html: null
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: null
  flutter_pdfview: ^1.3.2
  flutter_profile_picture: ^2.0.0
  flutter_spinkit: ^5.2.0
  get: null
  get_storage: ^2.1.1
  google_fonts: ^5.1.0
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  intl_phone_field: ^3.2.0
  mailer: ^6.0.1
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  photo_view: ^0.14.0
  pusher_channels_flutter: ^2.2.0
  sizer: ^2.0.15
  smooth_page_indicator: ^1.1.0
  supercharged: ^2.1.1
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_a.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
