// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZyGguXj8Xsx8_fTq8c9LoQTQ6U9bvLe4',
    appId: '1:591851412977:web:88303bd598b41f2d8bf850',
    messagingSenderId: '591851412977',
    projectId: 'amuba-mobile',
    authDomain: 'amuba-mobile.firebaseapp.com',
    storageBucket: 'amuba-mobile.appspot.com',
    measurementId: 'G-85HMVBG03N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2WMXraXGcj28-WzGTAUIXSdDsTUwjwts',
    appId: '1:591851412977:android:b6e6f9a6eb81c2be8bf850',
    messagingSenderId: '591851412977',
    projectId: 'amuba-mobile',
    storageBucket: 'amuba-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNeJSsJC0iUU4lX5-iIG3t_W2JuZfp82s',
    appId: '1:591851412977:ios:5a853210daa7e0708bf850',
    messagingSenderId: '591851412977',
    projectId: 'amuba-mobile',
    storageBucket: 'amuba-mobile.appspot.com',
    iosBundleId: 'com.entrepreneurAmuba.id',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNeJSsJC0iUU4lX5-iIG3t_W2JuZfp82s',
    appId: '1:591851412977:ios:0f1bd7904f7925428bf850',
    messagingSenderId: '591851412977',
    projectId: 'amuba-mobile',
    storageBucket: 'amuba-mobile.appspot.com',
    iosBundleId: 'com.entrepreneurAmuba.id.RunnerTests',
  );
}
